fastlane_version "2.215.0"

import_from_git(
  url: 'https://github.com/detroit-labs/fastlane-template',
  branch: "lanes",
  path: "fastlane/Lanes/Empty",
  dependencies: [
    "fastlane/Lanes/Fastfile-Blackboard",
    "fastlane/Lanes/Fastfile-Dependencies",
    "fastlane/Lanes/Fastfile-DetroitLabsKeychain",
    "fastlane/Lanes/Fastfile-Keychain",
    "fastlane/Lanes/Fastfile-Profiles",
    "fastlane/Lanes/Fastfile-ProjectKeychain",
    "fastlane/Lanes/Fastfile-Release",
    "fastlane/Lanes/Fastfile-SwiftFormat",
    "fastlane/Lanes/Fastfile-SwiftLint",
    "fastlane/Lanes/iOS/Fastfile-Build",
    "fastlane/Lanes/iOS/Fastfile-Test",
    "fastlane/Lanes/iOS/Fastfile-Upload",
    "fastlane/Lanes/iOS/Fastfile-Xcode"
  ]
)

default_platform :ios

platform :ios do

  before_all do
    installKeychains
    installProfiles
    prepareXcode
  end

  after_all do
    cleanupXcode
    removeKeychains
  end

  error do
    cleanupXcode
    removeKeychains
  end
  
end
