fastlane_version "2.109.0"

default_platform :ios

platform :ios do

  before_all do
    installKeychainsIfPossible
    xcversion(version: ENV["XCODE_VERSION"] || '~> 11.4')
    if !ENV["SKIP_COCOAPODS"]
      cocoapods(silent: true, try_repo_update_on_error: true)
    end
  end
  
  after_all do |lanes, options|
    cleanup(options)
    removeKeychainsIfPossible
  end

  desc "Runs all the tests."
  lane :runTests do
    simctl(type: ENV["DEVICE"] || 'iPhone 11 Pro',
           block: lambda { |other_action, device|
      other_action.scan(output_types: "junit",
                        device: device.name)
    })
  end

  desc "Sets the version number to the given version or, if none is given, increments it."
  lane :incrementBuildNumber do |options|
    if options[:build].nil?
      increment_build_number
    else
      increment_build_number(build_number: options[:build])
    end
  end

  desc "Sets the build number to the current commit count."
  lane :setBuildNumberToCommitCount do
    increment_build_number(build_number: number_of_commits)
  end

  desc "Build the archive and ipa with options (configuration (Release), include_bitcode (false), export_method (enterprise)), export_options ({})."
  lane :build do |options|
    options[:configuration] ||= "Release"
    options[:include_bitcode] ||= false
    options[:export_method] ||= "enterprise"
    options[:export_options] ||= {}
    
    installProfiles
    
    gym(
      configuration: options[:configuration],
      include_bitcode: options[:include_bitcode],
      export_method: options[:export_method],
      export_options: options[:export_options]
    )
  end
  
  desc "Upload a local IPA to Crashlytics with (group)."
  desc "#### Options"
  desc " * **`generate_changelog`**: Whether or not to generate a changelog as the release notes (boolean – default: `false`)"
  desc " * **`changelog_type`**: The type of changelog to generate (e.g. `\"git\"`, `\"jenkins\"`, `\"pr\"` – default: `\"git\"`)"
  desc " * **`release_notes`**: A string to set as the release notes; overrides any generated changelog."
  lane :uploadToCrashlytics do |options|
    options[:generate_changelog] ||= false
    options[:changelog_type] ||= "git"

    raise "uploadToCrashlytics: A Crashlytics group must be passed as an option." unless options[:group]

    unless options.key?(:release_notes)
      if options[:generate_changelog] == true
        case options[:changelog_type]
          when "jenkins"
            make_changelog_from_jenkins

          when "pr"
            UI.error("uploadToCrashlytics: Environment variable for PR ID is not set (ghprbPullId).") unless ENV.key?("ghprbPullId")
            options[:release_notes] = "PR: ##{ENV["ghprbPullId"]}\nBranch: (#{ENV["GIT_BRANCH"]})\nPR Link: #{ENV["ghprbPullLink"]}"

          when "git"
            changelog_from_git_commits

          else 
            UI.error("Unrecognized changelog_type: #{options[:changelog_type]}")
        end
      end
    end
    
    crashlytics(
      groups: options[:group],
      notes: options[:release_notes], # if release_notes is nil, this will be overriden by any generated changelog.
      notifications: true
    )
  end

  desc "Build and upload to Crashlytics with (configuration (Release)), (include_bitcode (false)), (export_method (enterprise)), (export_options ({})) and (group)."
  lane :beta do |options|
    options[:configuration] ||= "Release"
    options[:include_bitcode] ||= false
    options[:export_method] ||= "enterprise"
    options[:generate_changelog] ||= false
    options[:export_options] ||= {}

    raise "beta: A Crashlytics group must be passed as an option." unless options[:group]

    build(configuration: options[:configuration], 
      include_bitcode: options[:include_bitcode], 
      export_method: options[:export_method],
      export_options: options[:export_options]
    )

    uploadToCrashlytics(
      group: options[:group], 
      generate_changelog: options[:generate_changelog], 
      changelog_type: options[:changelog_type], 
      release_notes: options[:release_notes]
    )
  end
  
  desc "Upload a local IPA to Firebase App Distribution with (app_id) and (groups)."
  desc "#### Options"
  desc " * **`generate_changelog`**: Whether or not to generate a changelog as the release notes (boolean – default: `false`)"
  desc " * **`changelog_type`**: The type of changelog to generate (e.g. `\"git\"`, `\"jenkins\"`, `\"pr\"` – default: `\"git\"`)"
  desc " * **`release_notes`**: A string to set as the release notes; overrides any generated changelog."
  desc " * **`firebase_cli_token`**: The Firebase CLI token. (string - default: The `FIREBASE_TOKEN` environment variable.)"
  lane :uploadToFirebase do |options|
    options[:generate_changelog] ||= false
    options[:changelog_type] ||= "git"
    options[:firebase_cli_token] ||= ENV["FIREBASE_TOKEN"]

    raise "uploadToFirebase: An app ID must be passed as an option (e.g. `\"1:123456789:ios:abcd1234\"`)." unless options[:app_id]
    raise "uploadToFirebase: A tester group must be passed as an option." unless options[:groups]
    raise "uploadToFirebase: A CLI token must be provided, either through the firebase_cli_token parameter or FIREBASE_TOKEN environement variable." unless options[:firebase_cli_token]

    unless options.key?(:release_notes)
      if options[:generate_changelog] == true
        case options[:changelog_type]
          when "jenkins"
            make_changelog_from_jenkins

          when "pr"
            UI.error("uploadToCrashlytics: Environment variable for PR ID is not set (ghprbPullId).") unless ENV.key?("ghprbPullId")
            options[:release_notes] = "PR: ##{ENV["ghprbPullId"]}\nBranch: (#{ENV["GIT_BRANCH"]})\nPR Link: #{ENV["ghprbPullLink"]}"

          when "git"
            changelog_from_git_commits

          else
            UI.error("Unrecognized changelog_type: #{options[:changelog_type]}")
        end
      end
    end

    firebase_app_distribution(
      firebase_cli_token: options[:firebase_cli_token],
      app: options[:app_id],
      release_notes: options[:release_notes],
      groups: options[:groups]
    )
  end

  # Custom actions
  
  desc "Builds and uploads to Crashlytics a QA build."
  lane :betaQA do
    incrementBuildNumber
    
    raise "betaQA: A Crashlytics group must be provided through the CRASHLYTICS_QA_GROUP environment variable." unless ENV["CRASHLYTICS_QA_GROUP"]
    
    beta(group: ENV["CRASHLYTICS_QA_GROUP"])
    
    commit_version_bump(message: "Automatically bumping build number to #{lane_context[SharedValues::BUILD_NUMBER]}.")
    push_to_git_remote
  end
  
  desc "Deletes the archive generated by gym."
  lane :cleanupArchive do |options|
    if ("#{lane_context[SharedValues::XCODEBUILD_ARCHIVE]}" != "") && !(options[:keepArchive] || false)
      sh "rm -r \"#{File.dirname(lane_context[SharedValues::XCODEBUILD_ARCHIVE])}\" || :"
    end
  end
  
  desc "Kills the simulator and background process."
  lane :cleanupSimulator do
    # attempt to quit simulators nicely
    sh "xcrun simctl shutdown booted"
    # kill simulator
    sh "killall Simulator || :"
    # kill SimulatorService
    sh "killall -9 com.apple.CoreSimulator.CoreSimulatorService || :"
  end
  
  desc "Cleanup simulator and build archives."
  lane :cleanup do |options|
    cleanupSimulator
    cleanupArchive(options)
  end
  
end

desc "Installs any provisioning profiles in $PROFILE_DIRECTORY, relative to Fastlane's execution path."
lane :installProfiles do
  raise "installProfiles: PROFILE_DIRECTORY environment variable required." unless ENV["PROFILE_DIRECTORY"]
  
  Dir.glob("#{ENV["PROFILE_DIRECTORY"]}/*.mobileprovision") do |profile|
    FastlaneCore::ProvisioningProfile.install(profile)
  end
end

desc "Updates project dependencies in Bundler and CocoaPods, then sends a pull request if there are changes"
desc "#### Options"
  desc " * **`branchname`**: Accepts an optional value to set the dependency updater branch. If no value is passed in, it will default to the ENV variable name."
  desc " * **`base`**: Accepts an optional value to set the base branch for the created dependency update PR. If no value is passed in, it will default to master." 
  desc " * **`pullRequestTitle`**: Accepts an optional value to set the title for the created dependency update PR. If no value is passed in, it will default to Update Dependencies."
lane :updateDependencies do |options|
    options[:branchname] ||= ENV["UPDATE_DEPENDENCIES_BRANCH"]
    options[:base] ||= "master"
    options[:pullRequestTitle] ||= "Update Dependencies"

    fastlane_require 'fastlane-plugin-git_status'

    xcversion(version: ENV["XCODE_VERSION"] || '~> 11.3')
    bundle_update if File.exist?("../Gemfile.lock")
    cocoapods_update if File.exist?("../Podfile.lock")
    carthage(command: "update", no_build: true) if File.exist?("../Cartfile.resolved")

    sendUpdatePullRequest(
      branchname: options[:branchname],
      base: options[:base],
      pullRequestTitle: options[:pullRequestTitle]
    ) unless git_status.empty?
end

desc "Sends a pull request with the current changes to dependencies"
lane :sendUpdatePullRequest do |options|
    options[:branchname] ||= ENV["UPDATE_DEPENDENCIES_BRANCH"]
    options[:base] ||= "master"
    options[:pullRequestTitle] ||= "Update Dependencies"

    fastlane_require 'fastlane-plugin-git_status'

    branchname = options[:branchname]
    base = options[:base]
    
    create_git_branch(
      branchname: branchname
    )

    checkout_git_branch(
      branchname: branchname
    )

    git_add(
      path: "."
    )

    git_commit(
      path: ".",
      message: "Update dependencies"
    )

    push_to_git_remote(
      remote: "origin",
      local_branch: branchname,
      remote_branch: branchname,
      force: true,
      tags: false
    )

    create_pull_request(
      api_token: ENV["GITHUB_TOKEN"],
      repo: ENV["GITHUB_REPO"],
      head: branchname,
      base: base,
      title: options[:pullRequestTitle]
    )
end

desc "Installs the DL and project keychains if provided. This is a transitional API that should be removed once all projects move to keychain injections."
lane :installKeychainsIfPossible do
  if ENV["DL_KEYCHAIN_PATH"]
    UI.message("Installing DL keychain...")
    installDLKeychain
  end
  
  if ENV["PROJECT_KEYCHAIN_PATH"]
    UI.message("Installing project keychain...")
    installProjectKeychain
  end
end

desc "Removes the DL and project keychains if provided. This is a transitional API that should be removed once all projects move to keychain injections."
lane :removeKeychainsIfPossible do
  if ENV["DL_KEYCHAIN_PATH"]
    UI.message("Removing DL keychain...")
    removeDLKeychain
  end
  
  if ENV["PROJECT_KEYCHAIN_PATH"]
    UI.message("Removing project keychain...")
    removeProjectKeychain
  end
end

desc "Installs the DL keychain. Must provide path (or DL_KEYCHAIN_PATH) and password (or DL_KEYCHAIN_PASSWORD) parameters."
lane :installDLKeychain do |options|
  path = options[:path] ||= ENV["DL_KEYCHAIN_PATH"]
  password = options[:password] ||= ENV["DL_KEYCHAIN_PASSWORD"]
  
  raise "installDLKeychain requires a path parameter or DL_KEYCHAIN_PATH to be set." unless path
  raise "installDLKeychain requires a password parameter or DL_KEYCHAIN_PASSWORD to be set." unless password
  
  installKeychain(path: path, password: password)
end

desc "Installs the project keychain from a path relative to the root of the project. Must provide path (or PROJECT_KEYCHAIN_PATH), and password (or PROJECT_KEYCHAIN_PASSWORD) parameters."
lane :installProjectKeychain do |options|
  path = options[:path] ||= ENV["PROJECT_KEYCHAIN_PATH"]
  password = options[:password] ||= ENV["PROJECT_KEYCHAIN_PASSWORD"]
  
  raise "installProjectKeychain requires a name paramter or PROJECT_KEYCHAIN_PATH to be set." unless path
  raise "installProjectKeychain requires a password paramter or PROJECT_KEYCHAIN_PASSWORD to be set." unless password
  
  installKeychain(path: path, password: password)
end

desc "Installs a keychain by first copying it. Requires the keychain file path and password parameters."
lane :installKeychain do |options|
  path = options[:path]
  password = options[:password]
  
  raise "installKeychain requires a path parameter." unless path
  raise "installKeychain requires a password parameter." unless password
  
  name = File.basename(path, File.extname(path))
  copy_name = "#{name}Copy.keychain"
  
  Dir.chdir("..") do
    UI.message("Copying keychain named #{name} to #{copy_name}...")
    FileUtils.cp(path, copy_name)
    UI.message("Unlocking keychain named #{copy_name}...")
    unlock_keychain(path: File.join(Dir.pwd, copy_name), password: password)
  end
end

desc "Remove the Detroit Labs keychain. Requires the DL keychain path, or for DL_KEYCHAIN_PATH to be set."
lane :removeDLKeychain do |options|
  path = options[:path] ||= ENV["DL_KEYCHAIN_PATH"]
  
  raise "removeDLKeychain requires path parameter or DL_KEYCHAIN_PATH to be set." unless path
  
  name = File.basename(path, File.extname(path))
  removeKeychain(name: name)
end

desc "Remove the project keychain. Requires the project keychain path, or for PROJECT_KEYCHAIN_PATH to be set."
lane :removeProjectKeychain do |options|
  path = options[:path] ||= ENV["PROJECT_KEYCHAIN_PATH"]
  
  raise "removeProjectKeychain requires path parameter or PROJECT_KEYCHAIN_PATH to be set." unless path
  
  name = File.basename(path, File.extname(path))
  removeKeychain(name: name)
end

desc "Removes a keychain by name by removing {name}Copy."
lane :removeKeychain do |options|
  name = options[:name]
  
  raise "removeKeychain requires a name." unless name
  
  copy_name = "#{name}Copy"
  
  UI.message("Deleting keychain named #{copy_name}...")
  delete_keychain(name: copy_name)
end
